name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Delete merged branch
        if: github.event.pull_request.head.ref != 'development'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Deleting branch: $BRANCH"
          gh api \
            -X DELETE \
            "repos/${{ github.repository }}/git/refs/heads/$BRANCH"
