name: Deploy to Virtual Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SERVER_IP }}

    - name: Run commands on remote server
      run: |
        ssh root@${{ secrets.SERVER_IP }} "bash -s" << 'EOF'
        echo "Connection successful! This is a test log."
        EOF
