name: Deploy to Virtual Server

on:
  push:
    branches:
      - main

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Test Discord deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        passphrase: ${{secrets.SSH_PASSPHRASE}} 
        script: |
          echo "Stopping and removing existing Discord bot container (if it exists)..."
          docker stop discord-bot || true
          docker rm discord-bot || true
          
          echo "Removing old Docker image for Discord bot..."
          docker rmi my-discord-bot:latest || true
          
          echo "Building new Docker image for Discord bot..."
          cd /root/Discord_BOT
          echo "Pulling the latest code changes"
          git pull
          docker build -t my-discord-bot:latest .
          
          echo "Running new Discord bot container..."
          docker run -d --name discord-bot my-discord-bot:latest
