name: Deploy to Virtual Server

on:
  push:
    branches:
      - main  # Run the workflow when a push is made to the 'main' branch

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Discord bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        script: |
          echo "Stopping existing Discord bot container..."
          docker stop discord-bot || true
          
          echo "Removing existing Discord bot container..."
          docker rm discord-bot || true

          echo "Removing old Docker image for Discord bot..."
          docker rmi my-discord-bot:latest || true

          echo "Building new Docker image for Discord bot..."
          cd ${{secrets.DEPLOY_PATH}}
          docker build -t my-discord-bot:latest .

          echo "Running new Discord bot container..."
          docker run -d --name discord-bot my-discord-bot:latest
