name: Deploy to Virtual Server

on:
  push:
    branches:
      - main

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Test Discord deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        passphrase: ${{secrets.SSH_PASSPHRASE}}  # Add this line to provide the passphrase
        script: |
          echo "Deployment to the virtual server is starting..."
