name: Deploy to Virtual Server

on:
  push:
    branches:
      - main

jobs:
  remove_container:
    name: Remove Old Discord Bot Container
    runs-on: ubuntu-latest
    steps:
    - name: Remove old Discord bot container
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        passphrase: ${{secrets.SSH_PASSPHRASE}} 
        script: |
          echo "Stopping and removing existing Discord bot container (if it exists)..."
          docker stop discord-bot || true
          docker rm discord-bot || true
          
          echo "Removing old Docker image for Discord bot..."
          docker rmi my-discord-bot:latest || true

  build_image:
    name: Build Discord Bot Image
    runs-on: ubuntu-latest
    needs: remove_container 
    steps:
    - name: Build new Docker image for Discord bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        passphrase: ${{secrets.SSH_PASSPHRASE}} 
        script: |
          echo "Building new Docker image for Discord bot..."
          cd /root/Discord_BOT
          echo "Pulling the latest code changes..."
          git pull
          docker build -t my-discord-bot:latest .
          
          echo "Running new Discord bot container..."
          docker run -d --name discord-bot my-discord-bot:latest

  check_logs:
    name: Check Discord Bot Logs
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - name: Check Docker container logs
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        passphrase: ${{secrets.SSH_PASSPHRASE}} 
        script: |
          echo "Checking if the Docker container is running..."
          docker ps | grep discord-bot
          
          echo "Fetching logs from the Discord bot container..."
          docker logs discord-bot
