name: Deploy to Virtual Server

on:
  push:
    branches:
      - main  # Run the workflow when a push is made to the 'main' branch

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Test Discord deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        script: |
          echo "Deployment to the virtual server is starting..."
