name: Deploy to Virtual Server

on:
  push:
    branches:
      - main

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Test Discord deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        key: ${{secrets.DISCORD_SECRET}}
        port: 22
        script: |
          echo "Stopping and removing existing Discord bot container (if it exists)..."
          docker stop discord-bot || true  # Stop the container if running
          docker rm discord-bot || true    # Remove the container if it exists
          
          echo "Removing old Docker image for Discord bot..."
          docker rmi my-discord-bot || true  # Remove the image

          echo "Building new Docker image for Discord bot..."
          docker build -t my-discord-bot .

          echo "Running new Discord bot container..."
          docker run -d --name discord-bot my-discord-bot
